### ISSUE TITLE
Readme is out-of-sync

### ISSUE THREAD

**Issue by ctr26** [uhlmanngroup/MorphoDynamicsPipe#1]
- Currently refers to morphodynamics.smk which is missing/has been changed 
- Can drop the -s arg if the main entry point to the pipeline is Snakefile

**Comment by ctr26** [comment]
It's also possible to change the hardcoded paths (like 1_data) to be declared in a default config file

**Comment by spectralnanodiamond** [comment]
new snakemake file path has been updated in the readme
data path can currently be changed in the snakemake file
